//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedFocus.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RedFocus.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 About information coming soon... 的本地化字符串。
        /// </summary>
        internal static string About_ComingSoon {
            get {
                return ResourceManager.GetString("About_ComingSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        internal static string About_Title {
            get {
                return ResourceManager.GetString("About_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RedFocus 的本地化字符串。
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chinese 的本地化字符串。
        /// </summary>
        internal static string Language_Chinese {
            get {
                return ResourceManager.GetString("Language_Chinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 English 的本地化字符串。
        /// </summary>
        internal static string Language_English {
            get {
                return ResourceManager.GetString("Language_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset 的本地化字符串。
        /// </summary>
        internal static string Main_Reset {
            get {
                return ResourceManager.GetString("Main_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        internal static string Menu_Settings {
            get {
                return ResourceManager.GetString("Menu_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language 的本地化字符串。
        /// </summary>
        internal static string Options_Language {
            get {
                return ResourceManager.GetString("Options_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Options 的本地化字符串。
        /// </summary>
        internal static string Options_Title {
            get {
                return ResourceManager.GetString("Options_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Starting a new period of focused work, keep it up! 的本地化字符串。
        /// </summary>
        internal static string Start_FocusTime {
            get {
                return ResourceManager.GetString("Start_FocusTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enjoy a long break! 的本地化字符串。
        /// </summary>
        internal static string Start_LongBreak {
            get {
                return ResourceManager.GetString("Start_LongBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Take a break and relax for a moment! 的本地化字符串。
        /// </summary>
        internal static string Start_ShortBreak {
            get {
                return ResourceManager.GetString("Start_ShortBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Blue Theme 的本地化字符串。
        /// </summary>
        internal static string Theme_Blue {
            get {
                return ResourceManager.GetString("Theme_Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dark Theme 的本地化字符串。
        /// </summary>
        internal static string Theme_Dark {
            get {
                return ResourceManager.GetString("Theme_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Light Theme 的本地化字符串。
        /// </summary>
        internal static string Theme_Light {
            get {
                return ResourceManager.GetString("Theme_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Focus 的本地化字符串。
        /// </summary>
        internal static string TimerConfig_Focus {
            get {
                return ResourceManager.GetString("TimerConfig_Focus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Long Break 的本地化字符串。
        /// </summary>
        internal static string TimerConfig_LongBreak {
            get {
                return ResourceManager.GetString("TimerConfig_LongBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rounds 的本地化字符串。
        /// </summary>
        internal static string TimerConfig_Rounds {
            get {
                return ResourceManager.GetString("TimerConfig_Rounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Short Break 的本地化字符串。
        /// </summary>
        internal static string TimerConfig_ShortBreak {
            get {
                return ResourceManager.GetString("TimerConfig_ShortBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Timer 的本地化字符串。
        /// </summary>
        internal static string TimerConfig_Title {
            get {
                return ResourceManager.GetString("TimerConfig_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FOCUS 的本地化字符串。
        /// </summary>
        internal static string TimerState_Focus {
            get {
                return ResourceManager.GetString("TimerState_Focus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LONG BREAK 的本地化字符串。
        /// </summary>
        internal static string TimerState_LongBreak {
            get {
                return ResourceManager.GetString("TimerState_LongBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SHORT BREAK 的本地化字符串。
        /// </summary>
        internal static string TimerState_ShortBreak {
            get {
                return ResourceManager.GetString("TimerState_ShortBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start 的本地化字符串。
        /// </summary>
        internal static string TimerState_Start {
            get {
                return ResourceManager.GetString("TimerState_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Time to focus! 的本地化字符串。
        /// </summary>
        internal static string TimeTo_Focus {
            get {
                return ResourceManager.GetString("TimeTo_Focus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Time to Long Break! 的本地化字符串。
        /// </summary>
        internal static string TimeTo_LongBreak {
            get {
                return ResourceManager.GetString("TimeTo_LongBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Time to Short Break! 的本地化字符串。
        /// </summary>
        internal static string TimeTo_ShortBreak {
            get {
                return ResourceManager.GetString("TimeTo_ShortBreak", resourceCulture);
            }
        }
    }
}
