//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedFocus.Properties;

using System.Globalization;
using System.Resources;
using System.ComponentModel;

/// <summary>
///   A strongly-typed resource class, for looking up localized strings, etc.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
[System.Diagnostics.DebuggerNonUserCode()]
[System.Runtime.CompilerServices.CompilerGenerated()]
public class Resources : INotifyPropertyChanged
{
    private static ResourceManager? resourceMan;
private static CultureInfo? resourceCulture;
    private static Resources? _instance;

    public static Resources Instance => _instance ??= new Resources();

 public event PropertyChangedEventHandler? PropertyChanged;

    /// <summary>
    ///   Returns the cached ResourceManager instance used by this class.
    /// </summary>
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
    public static ResourceManager ResourceManager
{
        get
        {
            if (resourceMan is null)
 {
       ResourceManager temp = new ResourceManager("RedFocus.Properties.Resources", typeof(Resources).Assembly);
     resourceMan = temp;
    }
         return resourceMan;
  }
    }

    /// <summary>
    ///   Overrides the current thread's CurrentUICulture property for all
    ///   resource lookups using this strongly typed resource class.
    /// </summary>
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
    public static CultureInfo? Culture
    {
        get => resourceCulture;
  set
 {
            if (resourceCulture?.Name != value?.Name)
         {
          resourceCulture = value;
     Instance.OnPropertyChanged(null);
   }
  }
    }

    protected virtual void OnPropertyChanged(string? propertyName)
    {
      PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
    }

    /// <summary>
 ///   Looks up a localized string similar to RedFocus.
  /// </summary>
    public string AppTitle => ResourceManager.GetString("AppTitle", resourceCulture) ?? "RedFocus";

    /// <summary>
    ///   Looks up a localized string similar to Settings.
    /// </summary>
    public string Menu_Settings => ResourceManager.GetString("Menu_Settings", resourceCulture) ?? "Settings";

    /// <summary>
    ///   Looks up a localized string similar to FOCUS.
 /// </summary>
public string TimerState_Focus => ResourceManager.GetString("TimerState_Focus", resourceCulture) ?? "FOCUS";

    /// <summary>
    ///   Looks up a localized string similar to SHORT BREAK.
    /// </summary>
    public string TimerState_ShortBreak => ResourceManager.GetString("TimerState_ShortBreak", resourceCulture) ?? "SHORT BREAK";

    /// <summary>
    /// Looks up a localized string similar to LONG BREAK.
    /// </summary>
    public string TimerState_LongBreak => ResourceManager.GetString("TimerState_LongBreak", resourceCulture) ?? "LONG BREAK";

    /// <summary>
    ///   Looks up a localized string similar to Start.
    /// </summary>
  public string TimerState_Start => ResourceManager.GetString("TimerState_Start", resourceCulture) ?? "Start";

    /// <summary>
 ///   Looks up a localized string similar to Timer.
 /// </summary>
    public string TimerConfig_Title => ResourceManager.GetString("TimerConfig_Title", resourceCulture) ?? "Timer";

    /// <summary>
    ///   Looks up a localized string similar to Focus.
    /// </summary>
    public string TimerConfig_Focus => ResourceManager.GetString("TimerConfig_Focus", resourceCulture) ?? "Focus";

    /// <summary>
  ///Looks up a localized string similar to Short Break.
  /// </summary>
public string TimerConfig_ShortBreak => ResourceManager.GetString("TimerConfig_ShortBreak", resourceCulture) ?? "Short Break";

    /// <summary>
    ///   Looks up a localized string similar to Long Break.
    /// </summary>
    public string TimerConfig_LongBreak => ResourceManager.GetString("TimerConfig_LongBreak", resourceCulture) ?? "Long Break";

    /// <summary>
    ///   Looks up a localized string similar to Rounds.
    /// </summary>
    public string TimerConfig_Rounds => ResourceManager.GetString("TimerConfig_Rounds", resourceCulture) ?? "Rounds";

    /// <summary>
    ///   Looks up a localized string similar to Reset.
    /// </summary>
    public string Main_Reset => ResourceManager.GetString("Main_Reset", resourceCulture) ?? "Reset";

    /// <summary>
    ///   Looks up a localized string similar to About.
    /// </summary>
    public string About_Title => ResourceManager.GetString("About_Title", resourceCulture) ?? "About";

    /// <summary>
 ///   Looks up a localized string similar to About information coming soon....
    /// </summary>
  public string About_ComingSoon => ResourceManager.GetString("About_ComingSoon", resourceCulture) ?? "About information coming soon...";

    /// <summary>
    ///   Looks up a localized string similar to Options.
    /// </summary>
    public string Options_Title => ResourceManager.GetString("Options_Title", resourceCulture) ?? "Options";

    /// <summary>
    ///   Looks up a localized string similar to Language.
    /// </summary>
    public string Options_Language => ResourceManager.GetString("Options_Language", resourceCulture) ?? "Language";

    /// <summary>
    ///   Looks up a localized string similar to English.
    /// </summary>
    public string Language_English => ResourceManager.GetString("Language_English", resourceCulture) ?? "English";

    /// <summary>
    ///   Looks up a localized string similar to Chinese.
    /// </summary>
    public string Language_Chinese => ResourceManager.GetString("Language_Chinese", resourceCulture) ?? "Chinese";

    /// <summary>
    ///   Looks up a localized string similar to Dark Theme.
    /// </summary>
 public string Theme_Dark => ResourceManager.GetString("Theme_Dark", resourceCulture) ?? "Dark Theme";

    /// <summary>
    ///   Looks up a localized string similar to Blue Theme.
    /// </summary>
    public string Theme_Blue => ResourceManager.GetString("Theme_Blue", resourceCulture) ?? "Blue Theme";

    /// <summary>
    ///   Looks up a localized string similar to Light Theme.
    /// </summary>
    public string Theme_Light => ResourceManager.GetString("Theme_Light", resourceCulture) ?? "Light Theme";
}
